[package]
name = "termitex"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "TermiTex: asynchronous math rendering for Kitty-graphics terminals"
repository = "https://github.com/tingkai-c/TermiTex"

[dependencies]
libc = "0.2"
vt100 = "0.16"
vte = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
signal-hook = "0.3"
toml = "0.9"
ratex-render = { git = "https://github.com/erweixin/RaTeX", rev = "776c1d37bafa3bf445a0ab9377c55fe77f7a0133", features = ["embed-fonts"] }
ratex-layout = { git = "https://github.com/erweixin/RaTeX", rev = "776c1d37bafa3bf445a0ab9377c55fe77f7a0133" }
ratex-parser = { git = "https://github.com/erweixin/RaTeX", rev = "776c1d37bafa3bf445a0ab9377c55fe77f7a0133" }
ratex-types = { git = "https://github.com/erweixin/RaTeX", rev = "776c1d37bafa3bf445a0ab9377c55fe77f7a0133" }

[profile.release]
lto = "thin"

[dev-dependencies]
png = "0.17.16"
